version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.docker.localhost`)"
    volumes:
      - ./nginx/public:/public
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - proxy

  php_php_1:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./nginx/public:/public

  redis:
    image: redis:latest

  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
